---
name: Release a Terraform Module
on:
  workflow_dispatch:
    inputs:
      module_path:
        description: 'Module path'
        required: true
      version:
        description: 'module version'
        required: true
env:
  TFACTION_TARGET: ${{github.event.inputs.module_path}}
jobs:
  release-module:
    name: "release-module (${{github.event.inputs.module_path}})"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.3.6
      - uses: suzuki-shunsuke/tfaction/release-module@main
        with:
          version: ${{github.event.inputs.version}}
          module_path: ${{github.event.inputs.module_path}}
